# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6393598ffe5db21582ff5b243fe312bd9a09afbc73b76fe90682b3300948a65cf67726b1f60b3c52456763514156a3a66c7f83cb470e058c2f5cc0e1577f2840

test:
  secret_key_base: 439cf857c31476e185f9cfae9bb3d974ad2fd5019e4fa8bf4cd1cc80b254a59894376461733135f1a43ee0e462d3f0dfc01baa60d90f91f388361d44c77f17a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
